// Visual descriptions for the original gallery photos. Newer Work photos keep
// their existing metadata in work-photos.js.
const galleryDescriptions = {
  Charity: {
    "1.jpg": "People gathered around an outdoor table beside plants.",
    "2.jpg": "A group sitting together around a table in a living room.",
    "3.jpg": "People gathered in a bright room with chairs and a sofa.",
    "4.jpg": "A group standing together beside an indoor table.",
    "5.jpg": "Tables arranged outdoors beneath trees.",
    "6.png": "People presenting to a classroom of seated students.",
    "7.jpg": "Shopping carts filled with packaged food and drinks.",
    "8.jpg": "A group gathered around a picnic table beneath trees.",
    "9.jpg": "People sorting clothing and boxes in a room.",
    "10.png": "People walking and gathering among trees outdoors.",
    "11.jpg": "People sitting together in a room beside a television.",
    "12.jpg": "A group posing together indoors.",
    "13.jpg": "People arranging papers and supplies on a table.",
  },
  Chess: {
    "1.jpg": "A group posing together in a room with blue lighting.",
    "2.jpg": "A white chess-knight trophy resting on a table.",
    "3.jpg": "Three people posing together in a room.",
    "4.jpg": "Players seated at chessboards while another person leans over a table.",
    "5.jpg": "People gathered around chessboards on red-covered tables.",
    "6.jpg": "A bouquet being presented during a group gathering.",
    "7.jpg": "Two people playing chess across a small table.",
    "8.jpg": "A chessboard in the foreground with a player seated behind it.",
    "9.jpg": "Two people seated across a chessboard in a classroom.",
    "10.jpg": "Rows of tables and chairs set up with chessboards in a large hall.",
    "11.jpg": "A person standing in front of a logo-covered backdrop.",
    "12.jpg": "Two players seated at a chessboard on a red-covered table.",
    "13.jpg": "Chessboards and players at tables in an outdoor setting.",
  },
  Club: {
    "1.jpg": "A group posing behind a solar panel mounted on a wheeled frame.",
    "2.jpg": "A group gathered around a wheeled metal frame in a workshop.",
    "3.jpg": "A group posing in front of an indoor display wall.",
    "4.jpg": "A group standing outside a white building.",
    "5.jpg": "People examining an orange vehicle body in a workshop.",
    "6.jpg": "A blue electronic device with a screen and small sensors.",
    "7.jpg": "People gathered together in front of an indoor display wall.",
    "8.jpg": "A solar panel mounted on a wheeled metal frame.",
    "9.jpg": "People standing together in a workshop beside equipment.",
    "10.jpg": "Several people examining equipment on a workshop table.",
    "11.jpg": "A group standing together in a workshop.",
    "12.jpg": "Electronic components and small circuit boards arranged on a table.",
    "13.jpg": "A group posing indoors beside a green wall.",
    "14.jpg": "People working around equipment on a table.",
    "15.jpg": "A wheeled metal frame with a steering wheel outside a building.",
    "16.jpg": "A metal vehicle frame with a steering wheel in a room.",
    "17.jpg": "A wheeled metal frame parked in an outdoor work area.",
    "18.jpg": "People walking through an outdoor storage area with metal parts.",
    "19.jpg": "A person standing beside heavy machinery in an outdoor yard.",
    "20.jpg": "A person seated at the steering wheel of a metal vehicle frame.",
    "21.jpg": "A person seated in a small open-frame vehicle outdoors.",
    "22.jpg": "Two people examining a steering wheel on a metal frame.",
    "23.jpg": "A person working on a blue panel attached to a metal frame.",
    "24.jpg": "Two people standing behind a solar panel mounted on a wheeled frame.",
    "25.jpg": "Metal frames, wheels and tools laid out in an outdoor work area.",
    "26.jpg": "A participation certificate held in front of a steering wheel.",
    "27.jpg": "Hands adjusting a mechanical assembly between two wheels.",
    "28.jpg": "A handheld electronic device showing a person's face on its screen.",
    "29.jpg": "An audience watching a projected presentation in a classroom.",
    "30.jpg": "Two people beside electronic equipment on a workbench.",
    "31.jpg": "An outdoor banner beside a building.",
    "32.jpg": "An electronic assembly with exposed wiring and small components on a table.",
  },
  Work: {
    "1.jpg": "Printed cards with QR codes laid out together.",
    "2.jpg": "A white monogram on a black background.",
    "3.jpg": "A coding desk with a laptop, monitor and handwritten notes.",
    "4.jpg": "A shared workspace with computers and monitors.",
    "5.jpg": "Computer screens and equipment on a shared desk.",
    "6.jpg": "A group listening to a presentation with a projected timeline.",
    "7.jpg": "People seated in front of a projected timeline presentation.",
    "8.jpg": "Three people posing together in an indoor workspace.",
    "9.jpg": "A laptop and large monitor in an open workspace.",
    "10.jpg": "Hands on a keyboard below a screen displaying code.",
    "11.jpg": "Two people at a table with a tablet beside a window.",
    "12.jpg": "A laptop screen showing a visual diagram.",
    "13.jpg": "Two people speaking in a split-screen video.",
    "14.jpg": "Two people appearing together in a video frame.",
    "15.jpg": "Four people posing beside a table in an office.",
    "16.jpg": "A screen displaying source code beside a browser window.",
    "17.jpg": "Two people outdoors with the sea in the background.",
    "18.jpg": "Two laptops open on a meeting-room table.",
    "19.jpg": "A person seated in the back of a car.",
    "20.jpg": "A person giving a thumbs-up beside a desk with computer screens.",
    "21.jpg": "A workstation with multiple screens, a laptop and a keyboard.",
    "22.jpg": "Multiple computer screens displaying code and an application interface.",
    "23.jpg": "A meeting area with a table, chairs and a wall sign.",
    "24.jpg": "Two people working at a desk with a large monitor.",
    "25.jpg": "A laptop and external monitor displaying text and code.",
  },
};

export const galleryPhotos = Object.entries(galleryDescriptions).flatMap(([category, photos]) =>
  Object.entries(photos).map(([filename, description]) => ({
    src: `/images/${category}/${filename}`,
    alt: description,
    caption: description,
  }))
);
