export const workPhotos = [
  { src: "/work/saudade-qr-detail.webp", caption: "The Saudade QR-code T-shirt." },
  { src: "/work/saudade-shirt-photo.webp", caption: "A shirt photo received in Picture me by Saudade.", fit: "contain" },
  { src: "/work/welockin-schedule.webp", caption: "The WeLockIn schedule interface.", fit: "contain" },
  { src: "/work/start-hack-viseca.webp", caption: "Building the Viseca project in St. Gallen." },
  { src: "/work/development-desk.webp", caption: "A desk full of projects." },
  { src: "/work/scala-huffman.webp", caption: "Working through a Huffman coding exercise in Scala." },
  { src: "/work/welockin-development.webp", caption: "Behind the scenes of WeLockIn." },
  { src: "/work/saudade-received-photos.webp", caption: "The received-photos screen in Picture me by Saudade.", fit: "contain" },
  { src: "/work/saudade-tshirt.webp", caption: "The Saudade T-shirt design." },
  { src: "/work/saudade-tshirt-on-hanger.webp", caption: "From the Saudade idea to a physical shirt." },
  { src: "/work/mobile-development.webp", caption: "Mobile development at my desk." },
  { src: "/work/focus-session.webp", caption: "A focus session in progress." },
  { src: "/work/focus-session-interface.webp", caption: "A focus session at the desk." },
  { src: "/work/start-hack-workspace.webp", caption: "Another moment from the St. Gallen hackathon." },
  { src: "/work/scala-study-desk.webp", caption: "Scala notes, documentation, and code." },
  { src: "/work/desktop-development.webp", caption: "Working on a desktop application." },
  { src: "/work/assembly-development.webp", caption: "Assembly code at my desk." },
  { src: "/work/coding-workspace.webp", caption: "My everyday coding workspace." },
  { src: "/work/train-platform.webp", caption: "On the platform, ready to go." },
];
